import { Currency } from "@currency-converter/types";

export const SUPPORTED_CURRENCIES: Currency[] = [
  { name: "Algerian Dinar", code: "DZD", symbol: "د.ج", type: "classic" },
  { name: "Australian Dollar", code: "AUD", symbol: "$", type: "classic" },
  { name: "Baht", code: "THB", symbol: "฿", type: "classic" },
  { name: "Bitcoin", code: "BTC", type: "crypto" },
  { name: "BNB", code: "BNB", type: "crypto" },
  { name: "Boliviano", code: "BOB", symbol: "Bs.", type: "classic" },
  { name: "Brazilian Real", code: "BRL", symbol: "R$", type: "classic" },
  { name: "Cardano", code: "ADA", type: "crypto" },
  { name: "Cuban Peso", code: "CUP", symbol: "$", type: "classic" },
  { name: "Denar", code: "MKD", symbol: "ден", type: "classic" },
  { name: "Dobra", code: "STD", symbol: "Db", type: "classic" },
  { name: "Dogecoin", code: "DOGE", type: "crypto" },
  { name: "Euro", code: "EUR", symbol: "€", type: "classic" },
  { name: "Ethereum", code: "ETH", type: "crypto" },
  { name: "Forint", code: "HUF", symbol: "Ft", type: "classic" },
  { name: "Lempira", code: "HNL", symbol: "L", type: "classic" },
  { name: "Indian Rupee", code: "INR", symbol: "₹", type: "classic" },
  { name: "Kina", code: "PGK", symbol: "K", type: "classic" },
  { name: "Kip", code: "LAK", symbol: "₭", type: "classic" },
  { name: "Lebanese Pound", code: "LBP", symbol: "ل.ل", type: "classic" },
  { name: "Malaysian Ringgit", code: "MYR", symbol: "RM", type: "classic" },
  { name: "Mexican Peso", code: "MXN", symbol: "$", type: "classic" },
  { name: "Moroccan Dirham", code: "MAD", symbol: "د.م.", type: "classic" },
  { name: "Philippine Peso", code: "PHP", symbol: "₱", type: "classic" },
  { name: "Pound Sterling", code: "GBP", symbol: "£", type: "classic" },
  { name: "Riel", code: "KHR", symbol: "៛", type: "classic" },
  { name: "Rupiah", code: "IDR", symbol: "Rp", type: "classic" },
  { name: "Russian Ruble", code: "RUB", symbol: "₽", type: "classic" },
  { name: "Solana", code: "SOL", type: "crypto" },
  { name: "Swiss Franc", code: "CHF", symbol: "CHF", type: "classic" },
  { name: "Tether", code: "USDT", type: "crypto" },
  { name: "Toncoin", code: "TON", type: "crypto" },
  { name: "Tugrik", code: "MNT", symbol: "₮", type: "classic" },
  { name: "Tunisian Dinar", code: "TND", symbol: "د.ت", type: "classic" },
  { name: "Turkish Lira", code: "TRY", symbol: "₺", type: "classic" },
  { name: "Uganda Shilling", code: "UGX", symbol: "USh", type: "classic" },
  { name: "US Dollar", code: "USD", symbol: "$", type: "classic" },
  { name: "Vatu", code: "VUV", symbol: "Vt", type: "classic" },
  { name: "Won", code: "KRW", symbol: "₩", type: "classic" },
  { name: "XRP", code: "XRP", type: "crypto" },
  { name: "Yen", code: "JPY", symbol: "¥", type: "classic" },
  { name: "Yuan Renminbi", code: "CNY", symbol: "¥", type: "classic" },
];
